version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mysql://coco:loco@db/coco12
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql:5.7
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=coco
      - MYSQL_DATABASE=loco
    networks:
      - app-network
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
