version: '3'

services:
  web1:
    build: .
    volumes:
      - .:/app
      - ./data/db:/var/lib/postgresql/data
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  web2:
    build: .
    volumes:
      - .:/app
      - ./data/db:/var/lib/postgresql/data
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  web3:
    build: .
    volumes:
      - .:/app
      - ./data/db:/var/lib/postgresql/data
    environment:
      - FLASK_RUN_HOST=0.0.0.0

  loadbalancer:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
